version: '3.7'
services:
    api-mock:
        build: ../server
        environment:
            - 'PORT=8099'
        ports:
            - 8099:8099
    web:
        build:
            context: ../
            dockerfile: Dockerfile.web-cypress
        ports:
            - 8080:8080
        depends_on:
            - api-mock
        environment:
            - API_URL=http://localhost:8099
            - API_URL_INNSYN=http://localhost:8099
            - PUBLIC_PATH=/familie/sykdom-i-familien/soknad/endringsmelding-pleiepenger
            - HOST=localhost
    e2e:
        build: .
        depends_on:
            - web
        environment:
            - CYPRESS_video=false
            - CYPRESS_baseUrl=http://web:8080
# Dersom debugging er nødvendig
#    working_dir: /e2e
#    volumes:
#      - ./:/e2e

