# This workflow trigger on push to any branch
name: CI / CD
on:
    push:
        paths-ignore:
            - '**.md'
            - '.gitignore'
            - 'LICENCE'
            - 'CODEOWNERS'
        branches:

env:
    IMAGE: ghcr.io/${{ github.repository }}/endringsmelding-pleiepenger:${{ github.sha }}

jobs:
    test:
        name: Run tests
        if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev-') || github.event.deployment.payload.triggered
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v2.4.0
            - name: Sette opp Node
              uses: actions/setup-node@v2.5.1
            - name: Installere moduler
              run: npm ci
            - name: Bygge kode
              run: npm run build
            - name: Cypress tests
              run: npm run e2e:run

    build-code-and-push-docker:
        name: Build code and push docker image
        if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev-') || github.event.deployment.payload.triggered
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Hente kode
              uses: actions/checkout@v2.4.0
            - name: Sette opp Node
              uses: actions/setup-node@v2.5.1
            - name: Installere moduler
              run: npm ci
            - name: Bygge kode
              run: npm run build
            - name: Bygge Docker image
              run: docker build --tag ${IMAGE} .
            - name: Logge inn Github Package Registry
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}

    deploy-dev:
        name: Deploy to dev
        if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/main')
        needs: build-code-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.4.0
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/naiserator.yml
                  VARS: nais/dev-gcp.json
